# Generated by Django 4.2.30 on 2026-06-17 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='jogo',
            name='arena',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='jogo',
            name='genero',
            field=models.CharField(choices=[('M', 'Masculino'), ('F', 'Feminino')], default='F', max_length=1),
        ),
        migrations.AddField(
            model_name='jogo',
            name='pool',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='jogo',
            name='semana',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='jogo',
            name='set1_a',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='jogo',
            name='set1_b',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='jogo',
            name='set2_a',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='jogo',
            name='set2_b',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='jogo',
            name='set3_a',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='jogo',
            name='set3_b',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='jogo',
            name='set4_a',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='jogo',
            name='set4_b',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='jogo',
            name='set5_a',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='jogo',
            name='set5_b',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='time',
            name='bandeira',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='jogo',
            name='fase',
            field=models.CharField(choices=[('preliminar', 'Fase Preliminar'), ('quartas', 'Quartas de Final'), ('semi', 'Semifinal'), ('final', 'Final'), ('3lugar', 'Disputa de 3º Lugar')], default='preliminar', max_length=20),
        ),
        migrations.AlterUniqueTogether(
            name='time',
            unique_together={('nome', 'genero')},
        ),
    ]
