# Generated by Django 4.2.30 on 2026-06-17 19:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_jogo_arena_jogo_genero_jogo_pool_jogo_semana_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Destaque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semana', models.CharField(blank=True, max_length=30)),
                ('genero', models.CharField(choices=[('M', 'Masculino'), ('F', 'Feminino')], default='F', max_length=1)),
                ('tipo', models.CharField(choices=[('jogo', 'Destaque de jogo'), ('semana', 'Destaque semanal')], default='jogo', max_length=10)),
                ('jogador', models.CharField(max_length=100)),
                ('time', models.CharField(blank=True, max_length=100)),
                ('posicao', models.CharField(blank=True, max_length=50)),
                ('pontos', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('aces', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('bloqueios', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('ataque_pct', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True)),
                ('recepcao_pct', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True)),
                ('observacao', models.TextField(blank=True)),
                ('jogo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='destaques', to='core.jogo')),
            ],
            options={
                'ordering': ['-pontos'],
            },
        ),
    ]
