# Generated by Django 4.2.30 on 2026-06-17 20:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_destaque'),
    ]

    operations = [
        migrations.AddField(
            model_name='time',
            name='campeao',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='PalpiteCampeao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genero', models.CharField(choices=[('M', 'Masculino'), ('F', 'Feminino')], max_length=1)),
                ('pontos', models.PositiveSmallIntegerField(default=0)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('time', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='palpites_campeao', to='core.time')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='palpites_campeao', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('usuario', 'genero')},
            },
        ),
    ]
